home/urls.py
from django.urls import path
from home.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home')
    ]

ideas/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('ideas/', views.IdeaList.as_view(), name='ideas'),
    path('post/<slug:pk>/<str:activity_name>/', views.IdeaDetail.as_view(
    ), name='idea_detail'),
    path('delete/<slug:pk>', views.IdeaDelete.as_view(), name='idea_delete'),
    path('like/<slug:pk>', views.IdeaLike.as_view(), name='idea_like'),
    path('create/', views.IdeaCreate.as_view(), name='create'),
    path('edit/<slug:pk>', views.IdeaEdit.as_view(), name='idea_edit')
]

kidsbored/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('ideas/', include('ideas.urls')),
    path('accounts/', include('allauth.urls')),
]

ideas/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


class Idea(models.Model):
    """ A model to create Idea items """

    COST = [('free', 'Free'),
            ('10', 'Under £10 per person'),
            ('20', 'Under £20 per person'),
            ('30', 'Under £30 per person'),
            ('40', 'Under £40 per person'),
            ('50', 'Under £50 per person'),
            ('50+', 'Over £50 per person')
            ]

    AGE_RANGE = [
        ('all_ages', 'All Ages'),
        ('u1', 'Under 1'),
        ('1-2', '1 to 2 Years'),
        ('2-3', '2 to 3 Years'),
        ('3-5', '3 to 5 Years'),
        ('6-8', '6 to 8 Years'),
        ('9-11', '9 to 11 Years'),
        ('12-14', '12 to 14 Years'),
        ('15-17', '15 to 17 years'),
        ('u5', 'Under 5s'),
        ('u10', 'Under 10s'),
        ('o10', 'Over 10s')
    ]

    activity_name = models.CharField(max_length=200)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_ideas")
    updated_on = models.DateTimeField(auto_now=True)
    activity_location = models.CharField(max_length=200, unique=False)
    activity_website = models.URLField(
        max_length=200, blank=True)
    picture = CloudinaryField('image', default='placeholder')
    cost = models.CharField(max_length=200, choices=COST, default='free')
    age_range = models.CharField(
        max_length=200, choices=AGE_RANGE, default='all_ages')
    review = models.TextField(blank=True)
    likes = models.ManyToManyField(User, related_name='idea_likes', blank=True)

    class Meta:
        """ Order by Activity Name """
        ordering = ['activity_name']

    def __str__(self):
        return self.activity_name

    def number_of_likes(self):
        """ A function to count the number of likes """
        return self.likes.count()


class Comment(models.Model):
    """ A model to make a comment """
    idea = models.ForeignKey(
        Idea, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        """ Order by created on date """
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

ideas/forms.py
from .models import Comment, Idea
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class CommentForm(forms.ModelForm):
    """ A form to make a comment """
    class Meta:
        model = Comment
        fields = ('body',)


class IdeaForm(forms.ModelForm):
    """ A form to create an idea """
    class Meta:
        model = Idea
        fields = (
            'activity_name',
            'picture',
            'activity_location',
            'age_range',
            'cost',
            'activity_website',
            'review',
        )
        widgets = {
            'review': SummernoteWidget()
        }

home/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    """
    View to render homepage
    """
    template_name = 'home/index.html'

ideas/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (CreateView,
                                  DetailView, ListView, DeleteView, UpdateView)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Idea
from .forms import IdeaForm, CommentForm


class IdeaList(ListView):
    """ A view to return a list of ideas"""
    model = Idea
    queryset = Idea.objects.order_by('activity_name')
    template_name = 'ideas/ideas.html'
    paginate_by = 6


class IdeaDetail(DetailView):
    """ A view to see the idea in detail """
    def get(self, request, pk, *args, **kwargs):
        queryset = Idea.objects
        idea = get_object_or_404(queryset, pk=pk)
        comments = idea.comments.order_by("-created_on")
        liked = False
        if idea.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "ideas/ideas_detail.html",
            {
                "idea": idea,
                "comments": comments,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

    def post(self, request, pk, *args, **kwargs):
        """ A function to post the idea items """
        queryset = Idea.objects
        idea = get_object_or_404(queryset, pk=pk)
        comments = idea.comments.order_by("-created_on")
        liked = False
        if idea.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.idea = idea
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "ideas/ideas_detail.html",
            {
                "idea": idea,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )


class IdeaLike(CreateView):
    """ A view to like an idea """

    def post(self, request, pk):
        """ A function to add or remove a like """
        idea = get_object_or_404(Idea, pk=pk)

        if idea.likes.filter(id=request.user.id).exists():
            idea.likes.remove(request.user)
        else:
            idea.likes.add(request.user)

        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class IdeaCreate(CreateView):
    """ A view to create an idea """

    form_class = IdeaForm
    template_name = 'ideas/create_idea.html'
    success_url = "/ideas/ideas/"
    model = Idea

    def form_valid(self, form):
        """ If form is valid return to browse ideas """
        form.instance.author = self.request.user
        messages.success(self.request, 'Idea created successfully')
        return super(IdeaCreate, self).form_valid(form)


class IdeaDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """ A view to delete an idea """
    model = Idea
    success_url = "/ideas/ideas/"
    template_name = "ideas/idea_delete_conf.html"

    def test_func(self):
        return self.request.user == self.get_object().author


class IdeaEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """ A view to edit an idea """

    Model = Idea
    form_class = IdeaForm
    success_url = "/ideas/ideas/"
    template_name = "ideas/idea_edit_form.html"
    queryset = Idea.objects

    def form_valid(self, form):
        """ If form is valid return to browse ideas"""
        self.success_url + str(self.object.pk) + '/'
        messages.success(self.request, 'Idea updated successfully')
        return super().form_valid(form)

    def test_func(self):
        """ A function to test if the user is the author """
        return self.request.user == self.get_object().author

home/templates/home/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid text-center">
    <div class="row">
        </div>
        <!-- Hero Image-->
        <div class="col-md-10 offset-md-1">
            <img class="img-fluid hero-image border border-light "
                src="https://res.cloudinary.com/doakyrejw/image/upload/v1659094916/hero-image-kids-3-compress-4_xkealk.webp" 
                alt="Children smiling with ice cream on their faces ">
        </div>
        <div class="col-12">
            <!-- Title and about us section -->
            <h1 class="tag-line">
                Bored Kids?
                Welcome to
                Kidsbored!
            </h1>
            <p>
                Kidsboard is a place explore and share activity ideas to do with your kids.
                The idea is that you can log on and share as many ideas as you like.  From big days out to home
                crafts, if your kids had fun doing it let others know about it.  
            </p>
            <p>
                And when you are stuck for something to do, browse the ideas pages and see if you can get some inspiration.
            </p>
    </div>
</div>


{% endblock %}

ideas/templates/ideas/create_idea.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}


<div class="container">
    <!-- Create form header and information -->
    <h1>Share your Idea</h1>
    <p>Do you have your own fantasic idea to share?</p>
    <p>Complete the form below and let others know what it is!</p>
    <!-- Create idea form -->
    <form class="create_idea_form" method="POST" enctype="multipart/form-data">
        
        {% csrf_token %}

        {{form | crispy}}
    

        <button class="button" type="submit" class="btn-lg">Submit</button>






    </form>
</div>
{% endblock %}

ideas/templates/ideas/idea_delete_conf.html
{% extends "base.html" %}



{% block content %}


<div class="row col-md-8 offset-md-2 delete-idea">
    <div class="col-md-8 offset-md-2 p-3">
        <!-- Delete idea headig -->
        <h1 class="text-center">Delete Idea</h1>
        <div class="d-flex justify-content-center pt-3">
            <!-- Delete idea confirmation form-->
            <form method="post" class="text-center p-5">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ idea.activity_name }}"?</p>
                <input type="submit" value="Confirm" class="button">
            </form>
        </div>
    </div>
</div>

{% endblock %}

ideas/templates/ideas/idea_edit_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <!-- Edit idea form heading and information -->
    <h1>Edit your Idea</h1>
    <p>If you have any updates to your existing idea please update them here.</p>
    <!-- Edit idea form-->
    <form class="edit_idea_form" action="{% url 'idea_edit' idea.id %}" method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.id }}
        {{ form|crispy }}
        {{ form.media }}

        <input class="button" type="submit" value="Submit">
    </form>

</div>
{% endblock %}

ideas/templates/ideas/ideas.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1>Browse Ideas</h1>
        </div>
    </div>
    <div class="row">

        <!-- Ideas Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for idea in idea_list %}
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <div class="card-body">
                                {% if "placeholder" in idea.picture.url %}
                                <!-- Placeholder image-->
                                <img class="card-img-top ideas-page-pic" 
                                src="https://res.cloudinary.com/doakyrejw/image/upload/v1659164582/pexels-kampus-production-6299265_popbk1.jpg" 
                                alt="children running through a field with baloons">
                                {% else %}
                                <!-- User image -->
                                <img class="card-img-top ideas-page-pic" src="{{ idea.picture.url }}" alt="">
                                {% endif %}
                                <!-- Idea Author-->
                                <div>
                                    <p class="author">Author: {{ idea.author }}</p>
                                </div>
                                <!-- Activity name and link to idea detail page -->
                            <a href="{% url 'idea_detail' idea.pk idea.activity_name %}" class="idea-link">
                                <h2 class="card-title">{{ idea.activity_name }}</h2>
                            </a>
                            <hr>
                            <!-- date idea was updated on and number of likes -->
                            <p class="card-text h6">{{ idea.updated_on}}</p><i
                                    class=" card-text far fa-heart">{{ idea.number_of_likes }}</i>

                                
                            </div>
                        </div>
                    </div>
                <!-- starts a new row after every 3 ideas posted -->
                {% if forloop.counter|divisibleby:3 %}

            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- puts next page button at the bottom of the page when there are more than 6 ideas on a page-->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>


{% endblock %}

ideas/templates/ideas/ideas_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<!-- idea detail card -->
<div class="masthead">
    <div class="container pic-padding card">
        <div class="row g-0">
            <div class="col-md-6">
                <h1 class="idea-title"> {{ idea.activity_name }}</h1>
                <p class="idea-subtitle">{{ idea.author }} | {{ idea.updated_on }}</p>
            </div>

            <!-- Delete Idea -->
            {% if idea.author == request.user%}
            <div class="row-md-3">
                <div class="col-md-3 float-right ">
                    <span>
                        <a href="{% url 'idea_delete' idea.pk %}" class="delete large-icon"
                            aria-label="Click to delete idea">
                            <i class="far fa-trash-alt fa-2x"></i>
                        </a>
                    </span>
                    <!-- Edit Idea -->
                    <span>
                        <a href="{% url 'idea_edit' idea.pk %}" class="edit large-icon" aria-label="Click to edit idea">
                            <i class="far fa-edit fa-2x"></i>
                        </a>
                    </span>
                </div>
            </div>
            {% endif %}
            <div class="row">
                <div class="d-md-block col-md-12 card">
                    {% if "placeholder" in idea.picture.url %}
                    <!-- placeholder picture -->
                    <img class="card-img-top border border-light ideas-detail-pic"
                        src="https://res.cloudinary.com/doakyrejw/image/upload/v1659164582/pexels-kampus-production-6299265_popbk1.jpg"
                        alt="children running through a field with baloons">
                    {% else %}
                    <!-- uploaded picture -->
                    <img class="card-img-top border border-light ideas-detail-pic" src="{{ idea.picture.url }}" alt="">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb4 mt3">
            <div class="row">
                <div class="col-md-12">
                    <!-- Activity Website Address-->
                    <p> Activity Website:
                        <a href="{{ idea.activity_website }}" target="_blank" rel="noopener"
                            aria-label="Please visit the website linked to {{idea.activity_name}} (opens in a new window)">
                            {{ idea.activity_website }}</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col card mb4 mt3">
            <!-- Activity Cost -->
            <span>
                    Price:  {{ idea.cost }}
            </span>
            <!-- Activity Price Range -->
            <span>
                    Age Range:  {{ idea.age_range }}
            </span>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col card mb4 mt3 left top">
            <div class="card-body">
                <!-- Activity Review -->
                <p class="card-text">
                    {{ idea.review | safe }}
                </p>
                <div class="row">
                    <div class="col-1 like-comment">
                        <!-- check user is logged in -->
                        {% if user.is_authenticated %}
                        <!-- Form Button to like an idea, toggles button on and off again when clicked -->
                        <form class="d-inline" action="{% url 'idea_like' idea.pk %}" method="POST">
                            {% csrf_token %}
                            {% if liked %}
                            <button type="submit" name="idea_id" value="{{idea.pk}}" class="btn-like">
                                <i class="fas fa-heart"></i>
                            </button>
                            {% else %}
                            <button type="submit" name="idea_id" value="{{idea.pk}}" class="btn-like">
                                <i class="far fa-heart"></i>
                            </button>
                                {% endif %}
                        </form>
                        {% else %}

                        <span><i class="far fa-heart"></i></span>

                        {% endif %}
                        <!-- shows number of likes an idea has -->
                        <span>{{ idea.number_of_likes }}</span>
                    </div>
                    <!-- Shows number of comments an idea has -->
                    <div class="col-1 like-comment">
                        {% with comments.count as total_comments %}
                        <strong><i class="far fa-comments"></i>
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <!-- Comments section -->
            <h2>Comments:</h2>
            <div class="card-body">
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- Name of commentor-->
                        {{ comment.name }}
                        <span class=" card-text font-weight-normal">
                            <!-- Date comment was created on-->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The comment -->
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- Check if the user is logged in-->
                {% if user.is_authenticated %}
                <h3>Leave a comment:</h3>
                <!-- commenter username-->
                <p class="card-text">Posting as: {{ user.username }}</p>
                <!-- Comment form -->
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn button btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="kids, things to do with children, activities, sharing, bored kids, parents">
    <meta name="description" content="Kids Bored, an activity sharing ideas page for parents">
    <!-- bootstrap css link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- bootstrap js link -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    <!-- my css link -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- font awesome link -->
    <script src="https://kit.fontawesome.com/aad6cd9071.js" crossorigin="anonymous"></script>
    <title>Kidsbored</title>
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-light">
        <!-- Kidsbored Title -->
        <a class="navbar-brand" href="{% url 'home' %}">Kidsbored</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navigation list -->
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav text-end">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ideas' %}">Browse Ideas</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create' %}">Add Idea</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'account_login' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <!-- messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-4" id="msg">
                {% for message in messages %}
                {% include 'includes/toasts/toast.html' %}
                {% endfor %}
            </div>
        </div>
    </div>


    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Kidsbored</p>
        <p class="m-0 text-center text-white">Contact us at: kidsbored@google.com</p>
        <p class="m-0 text-center text-white">Follow us:
            <!-- Facebook link-->
            <a class="social-links" href="https://www.facebook.com" target="_blank" rel="noopener"
                aria-label="Please visit our Facebook Page (opens in a new tab)">
                <i class="fab fa-facebook-square ms-3"></i></a>
            <!-- Twitter link -->
            <a class="social-links" href="https://twitter.com" target="_blank" rel="noopener"
                aria-label="Please visit our Twitter Page (opens in a new tab)">
                <i class="fab fa-twitter-square ms-3"></i></a>
            <!-- Instagram link -->
            <a class="social-links" href="https://www.instagram.com/" target="_blank" rel="noopener"
                aria-label="Please visit our Instagram Page (opens in a new tab)">
                <i class="fab fa-instagram-square ms-3"></i></a>
            <!-- Youtube link -->
            <a class="social-links" href="https://youtube.com/" target="_blank" rel="noopener"
                aria-label="Please visit our Youtube Page (opens in a new tab)">
                <i class="fab fa-youtube-square ms-3"></i></a>
        </p>
    </footer>
    <script>
        setTimeout(function(){
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>


</body>

</html>

templates/includes/toasts/toast.html
<div class="toast custom-toast fade show">
    <div class="d-flex">
        <div class="toast-body">
            {{ message }}
        </div>
    </div>
</div>